steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: './'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'create', '--trigger-http', '--runtime', 'nodejs16', '--allow-unauthenticated']
  dir: './'
options:
  logging: NONE